---
deployment:
  tasks:
    # Đường dẫn đến thư mục nơi bạn muốn triển khai ứng dụng
    - export DEPLOYPATH=/home/eventhui/node/

    # Sao chép các tệp cần thiết vào thư mục triển khai
    - /bin/cp -R /home/eventhui/repositories/Event_HUIT_Server/* $DEPLOYPATH

    # Chạy lệnh để khởi động ứng dụng Node.js
    - cd $DEPLOYPATH
    - npm install
    - npm start &

    # Nếu bạn có một tệp cấu hình, ví dụ như .env, hãy sao chép nó
    - /bin/cp .env $DEPLOYPATH
